{
  " kind ": "order",
  " status ": "created",
  " order_id ": "ord_Xfsdjkfldsf",
  " external_order_id ": "xxxxxx123",
  " delivery_id ": "del_3vDjjkd21b",
  " place_details ": {
    " place_id ": "plc_uAJs7l1rREGmJnZFH_6RZA",
    " external_place_id ": "14d4d332-919b-46a3-b18f-48c2c0a1e816",
    " timezone ": "America/New_York"
  },
  " pickup_details ": {
    " display_name ": "FirstName LastInitial",
    " order_number ": 555,
    " pickup_time ": null
  },
  " subtotal ": 10,
  " tax ": 0.85,
  " items ": [
    {
      " id ": "oi_DFSIFSAMfkjdfo",
      " external_id ": "46d229a9-0d95-4e4c-a135-dc068dbd29f3",
      " name ": "Mongolian",
      " category_name ": "Rice Bowls",
      " base_price ": 0,
      " quantity ": 1,
      " modifer_lists ": [
        {
          " name ": "Protein Option",
          " modifiers ": [
            {
              " id ": "oim_HmbHOgQuQia3kSh3bUBvw",
              " external_id ": "57841aab-6861-421d-b593-a8852bf32627",
              " price ": 8.99,
              " name ": "Chicken"
            }
          ]
        },
        {
          " name ": "Rice Option",
          " modifiers ": [
            {
              " id ": "oim_HmbHOgQuQia3kSh3bUBvw",
              " external_id ": "57841aab-6861-421d-b593-a8852bf32627",
              " price ": 0,
              " name ": "White Rice"
            }
          ]
        }
      ]
    }
  ],
  "errors": "null"
}