{
"kind" : "event.order_updated",
"id" : "evt_iDPBFypsRCaY8ZfCbDhLYQ",
"created" : "2018-08-26T10:04:03Z",
"data" : {
"kind" : "order",
"status" : "submitted",
"order_id" : "ord_Xfsdjkfldsf",
"external_order_id" : null,
"delivery_id" : "del_3vDjjkd21b",
"place_details" : {
"place_id" : "plc_uAJs7l1rREGmJnZFH_6RZA",
"external_place_id" : "14d4d332-919b-46a3-b18f-48c2c0a1e816",
"timezone" : "America/New_York"
},
"pickup_details" : {
"display_name" : "FirstName LastInitial",
"order_number" : 555,
"pickup_time" : null
},
"subtotal" : 10.00,
"tax" : 0.85,
"items" :[
{
"id" : "oi_DFSIFSAMfkjdfo",
"external_id" : "14d4d332-919b-46a3-b18f-48c2c0a1e816",
"name" : "Mongolian",
"category_name" : "Rice Bowls",
"base_price" : 0.00,
"quantity" : 1,
"modifier_lists" : [ ]
}
],
"errors" : null
},
"order_id" : "ord_Xfsdjkfldsf",
"status" : "created"
}