{
  "kind": "event.order_updated",
  "id": "evt_xoitjiKsQfObGMzNCfg6qQ",
  "data": {
    "kind": "order",
    "order_id": "ord_C3YnjnUSSJiRije8kshQzA",
    "external_order_id": "abc_1235",
    "pickup_time": "2020-02-12T23:59:48.547602600Z"
  },
  "order_id": "ord_C3YnjnUSSJiRije8kshQzA",
  "status": "submitted",
  "created": "2020-02-11T23:20:55.547602600Z"
}