#%RAML 1.0 DataType
type: object
properties:
  street_address_1:
    description: First address line, which should NOT include a suite, unit number, etc.
    type: string
  
  street_address_2:
    description: Second address line, such as for a suite number
    type: string

  city:
    description: Name of the city for this location
    type: string

  state:
    description: 2-letter state code 
    type: string

  zip_code:
    description: 5-digit or extended zip code for this location
    type: string

  country:
    description: 2-letter country code for the location
    type: string







